### ISSUE TITLE
Generic data stewards in the Netherlands: who they are, what they do, and who they could become

### ISSUE THREAD

**Issue by Elisa-PyDay** [open-life-science/ols-4#1]
Project Lead: Elisa-PyDay

Mentor: cemonks and Alexandra Holinski (GitHub username not found)

Welcome to OLS-4! This issue will be used to track your project and progress during the program. Please use this checklist over the next few weeks as you start Open Life Science program :tada:.

***

Week 1 (week starting 13 September 2021): Meet your mentor!
- [ ] Meet mentor for 30 minutes 
- [ ] Create an account on [GitHub](https://github.com)
- [ ] Check if you have access to the HackMD notes set up for your meetings with your mentor
- [ ] Prepare to meet your mentor(s) by completing a short homework provided in your shared notes
- [ ] Complete **your own copy** of the [open leadership self-assessment](https://docs.google.com/document/d/1oQgdfj4lPnypAyb9_Ba0Zt7E8J5L6qMvuKwu0wgQsjs/edit?usp=sharing) and share it to your mentor 
  If you're a group, each teammate should complete this assessment individually. This is here to help you set your own personal goals during the program. No need to share your results, but be ready to share your thoughts with your mentor.
- [ ] Make sure you know when and how you'll be meeting with your mentor.

Before Week 2 (week starting 20 September 2021): Cohort Call (Welcome to Open Life Science!)
- [ ] Attend call or catch up via YouTube
- [ ] Create an issue on the [OLS-4 GitHub repository](https://github.com/open-life-science/ols-4/issues/new) for your OLS work and share the link to your mentor.
- [ ] Draft a brief vision statement using your goals

  [This lesson](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/) from the Open Leadership Training Series (OLTS) might be helpful

- [ ] Leave a comment on this issue with your draft vision statement & be ready to share this on the call
- [ ] Check the [Syllabus](https://openlifesci.org/ols-4) for notes and connection info for all the cohort calls.

Before Week 3 (week starting 27 September 2021): Meet your mentor!
- [ ] Meet mentor
- [ ] Look up two other projects and comment on their issues with feedback on their vision statement
- [ ] Complete this [compare and contrast assignment](https://docs.google.com/document/d/1ukvqDRIYfvCapVMdE5hWP-0MkLNJ9T65X43O7F336Ac/edit?usp=sharing) about current and desired community interactions and value exchanges
- [ ] Complete your Open Canvas ([instructions](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/), [canvas](https://docs.google.com/presentation/d/1MeJo0TyuMg_waLk1J4q9y1aAqKNMuRBlnmxEChSz-cQ/edit?usp=sharing))
- [ ] Share a link to your Open Canvas in your GitHub issue
- [ ] Start your [Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/)
- [ ] Comment on your issue with your draft Roadmap
- [ ] Suggest a cohort name at the bottom of the shared notes and vote on your favorite with a +1

Before Week 4: Cohort Call (Tooling and roadmapping for Open projects)
- [ ] Attend call or catch up via YouTube
- [ ] Look up two other projects and comment on their issues with feedback on their open canvas.

Week 5 and later
- [ ] Meet mentor
- [ ] Create a GitHub repository for your project
- [ ] Add the link to your repository in your issue
- [ ] Use your canvas to [start writing a `README.md` file](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), or landing page, for your project
- [ ] Link to your README in a comment on this issue
- [ ] Add an [open license](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/sharing-your-work-in-the-open/) to your repository as a file called `LICENSE.md`
- [ ] Add a [Code of Conduct](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-a-code-of-conduct/) to your repository as a file called `CODE_OF_CONDUCT.md`
- [ ] Invite new contributors to into your work!

This issue is here to help you keep track of work as you start Open Life Science program. Please refer to the [OLS-4 Syllabus](https://openlifesci.org/ols-4) for more detailed weekly notes and assignments past week 4.

Week 6 
- [ ] Attend call or catch up via YouTube

Week 7
- [ ] Meet mentor

Week 8
- [ ] Attend call or catch up via YouTube

Week 9
- [ ] Meet mentor

Week 10
- [ ] Attend call or catch up via YouTube

Week 11
- [ ] Meet mentor

Week 12
- [ ] Attend call or catch up via YouTube

Week 13
- [ ] Meet mentor

Week 14
- [ ] Attend call or catch up via YouTube

Week 15
- [ ] Meet mentor

**Comment by Elisa-PyDay** [comment]
Vision statement (before the cohort call on 22 September):
I am working with my colleagues, generic data stewards at Dutch universities, to understand their work and their training needs, and to identify possible career paths for and with them, so that these data stewards - including myself - can be more empowered to do their jobs, improve their skills and knowledge, and collaborate with their peers to improve research data management and open science support. I also hope that my project, and the openness of my project, will help faculty/disciplinary data stewards to collaborate better with their generic, centrally positioned, colleagues and it will help policy and HR advisors to draft policies that are helpful to both research support staff and researchers themselves, and to design personnel strategies that reflect (the diversity in) skills, knowledge and training needs present in this community.

**Comment by Elisa-PyDay** [comment]
New version of the vision statement after working with the Hemingway editor:
I want to understand the roles and training needs of generic data stewards at Dutch universities . I also want to  identify possible career paths for and with them. The goal is that these data stewards are more empowered to fulfill their roles and add to their skills and knowledge. They should also feel comfortable to collaborate with their peers. This will  improve research data management and open science support. By making the project open, I also hope that it will help generic and disciplinary data stewards to collaborate. This will help policy advisors to draft policies that will improve research support. The outcomes of this project reflect skills, knowledge and training needs present in this community.

**Comment by Elisa-on-GitHub** [comment]
Very late: link to my [README](https://github.com/Elisa-on-GitHub/Generic-data-stewards/blob/3310be7d3d093a92ee89f4d6bff37e4c3c4e7311/README.md)

**Comment by Elisa-on-GitHub** [comment]
I realised I never added my draft Roadmap, although I did create it. This was because I created it before we had the call where we were introduced to GitHub, and I forgot to add it afterwards. The overview below was just a draft, and I never updated it, so that shows nicely that updating is important and also easy to forget!
My initial Roadmap is below:

# Roadmap (draft) for “Generic Data Stewards in the Netherlands”

## Milestone nr. 1: Start recruiting participants
[] Post in the Slack group for the data stewards
[] Send around an email in the data stewards newsletter
[] Use personal (and local) networks
[] Ask colleague to spread it in their network

## Milestone nr. 2: Interview participants
[] Ask help for arranging the privacy aspects
[] Think of recording & transcription options
[] Ask help for producing the output

## Milestone nr. 3: Write!
[] Ask my colleague for the space to write the blogs
[] Write blog posts
[] Create interoperable output

The project worked out quite differently in the end, I will work on a hindsight document to learn from it.
